version: "3"
services:
  springboot-app:
    image: kalvad-test-docker
    restart: always
    build: .
    ports:
      - "9090:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
    - mysqldb
    command: sh -c './wait-for mysqldb:3306 -- npm start'
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: springdocker
      MYSQL_ROOT_PASSWORD: root
